### ISSUE TITLE
ERROR:  Could not find a valid gem 'sensu-plugins-slack' (>= 0) in any repository

### ISSUE THREAD

**Issue by vjanelle** [sensu-plugins/sensu-plugins-slack#1]
Following the instructions (but using the embedded sensu gem), I get:

```
$# /opt/sensu/embedded/bin/gem cert --add <(curl -Ls https://raw.githubusercontent.com/sensu-plugins/sensu-plugins.github.io/master/certs/sensu-plugins.pem)

Added '/CN=mattjones/DC=yieldbot/DC=com'
```

```
$# /opt/sensu/embedded/bin/gem install sensu-plugins-slack -P MediumSecurity

ERROR:  Could not find a valid gem 'sensu-plugins-slack' (>= 0) in any repository
ERROR:  Possible alternatives: sensu-plugins-riak, sensu-plugins-ssl, sensu-plugins-apache, sensu-plugins-aws, sensu-plugins-telapi
```

**Comment by dfinninger** [comment]
:+1: for this. I can't install the gem while following the same steps outlined here, or in Chef using the `sensu_gem` resource.

This also does not appear in RubyGems.

**Comment by mattyjones** [comment]
@dfinninger  Not all repos are built into gems yet.  I make this one happen this weekend.

**Comment by dfinninger** [comment]
@mattyjones sweet.

Is this plugin system not the "live" yet? I've seen the June date for shutting down the `sensu-community-plugins` repo, is that when these will be considered ready to go?

**Comment by mattyjones** [comment]
@dfinninger  Juy6th every repo will be in a Continuous Integration/Continuous Deployment pipeline and consequently will be built into gems and Github releases.

About half the plugins already are and more are completed as time allows but we are a small team and these things take time :stuck_out_tongue_winking_eye:   Feel free to request specific repos though :smile:

**Comment by dfinninger** [comment]
Ah, gotcha. Thanks for the effort!
