### ISSUE TITLE
Update README to include how to use the message template

### ISSUE THREAD

**Issue by mjulian** [sensu-plugins/sensu-plugins-slack#12]
The README only specifies the path to a template file, but doesn't say what that template should contain.

**Comment by analytically** [comment]
I'll happily accept a PR demonstrating a template file.

**Comment by mjulian** [comment]
I'd happily submit one, but I'm having to figure out how it works first, since there's no docs on it. ;)

**Comment by analytically** [comment]
Oh, that's a description field template file, in ERB (http://apidock.com/ruby/ERB). Can be plaintext too.

**Comment by analytically** [comment]
Optional, you can leave it out.

**Comment by mjulian** [comment]
Thanks, but honestly, that's not really helpful. Do you have examples in ERB or plaintext, showing how it can be used?

**Comment by analytically** [comment]
It's a text file.
