### ISSUE TITLE
payload_template example has render issues

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [sensu-plugins/sensu-plugins-slack#16]
Just an FYI the payload_template on the readme page fails to pass json validation due to conflicting quotation marks.

**Comment by tute26** [comment]
same problem here

**Comment by tute26** [comment]
well i fixed the template, 
`{
	"username": "Sensu",
	"icon_emoji": ":bell:",
	"channel": "#tests",
	"attachments": [{
			"fallback": "<%=@event[\"check\"][\"output\"]%>",
			"color": "<%=color %>",
			"title": "<%=@event[\"check\"][\"name\"]%> (<%= @event[\"client\"][\"name\"]%>)",
			"text": "<%=@event[\"check\"][\"output\"].gsub('\" ', ' \\\\ \"')%>"
		}
	]
}
`

**Comment by majormoses** [comment]
@tute26 any chance you could PR this?

**Comment by majormoses** [comment]
We have recently updated the documentation, I will close this out and if it is not clear please reply back and we can re-open it.
