### ISSUE TITLE
Payload template not working with multi-channel support

### ISSUE THREAD

**Issue by shaneramey** [sensu-plugins/sensu-plugins-slack#21]
I'm working off of the 0.1.2 release and cannot use a payload template for multi-channel support.

I have in my /etc/sensu/conf.d/slack_handler.json:
```
{
  "slack": {
    "webhook_url": "<%= @url_slack_integration %>",
    "payload_template": "/etc/sensu/conf.d/slack-payload.erb",
    "channels": {
      "default": ["#alerts"],
      "compulsory": ["#alerts"]
    }
  }
}
```

However the payload_template isn't being read, and instead a default output (which I can't modify) is generated.

**Comment by eheydrick** [comment]
Fixed via #22
