### ISSUE TITLE
Plugin is sending alerts even when events/clients are silenced

### ISSUE THREAD

**Issue by dzeleski** [sensu-plugins/sensu-plugins-slack#29]
After upgrading sensu to 26.3 and uchiwa 18.2 silenced events are still being triggered. Is this an issue with the handler not checking to see if the event is silenced? Or am I missing something else?

Thanks,
Dylan

**Comment by sroy-ingenu** [comment]
I am seeing this behavior as well.

**Comment by dzeleski** [comment]
This was fixed by using a filter. Sensu removed the built in filtering in 26.x
