### ISSUE TITLE
icon_emoji attribute not supported by multichannel plugin

### ISSUE THREAD

**Issue by fildred13** [sensu-plugins/sensu-plugins-slack#43]
As the title of this issue says, the icon_emoji attribute is not supported by the multichannel plugin. The README.md lists the attribute as valid for the multichannel plugin, but support for it is not present in the code itself.

**Comment by majormoses** [comment]
@fildred13 thanks for reporting that, any chance you would be willing to submit a PR to add this or update the documentation?

**Comment by majormoses** [comment]
closed via #44 and released in: https://rubygems.org/gems/sensu-plugins-slack/versions/1.3.0
