### ISSUE TITLE
Exception raised when configured field is not present

### ISSUE THREAD

**Issue by mnuessler** [sensu-plugins/sensu-plugins-slack#6]
If the `fields` array in the handler configuration contains an entry of a field that is not present, an exception is raised. The problems seems to be at this at [this line](https://github.com/sensu-plugins/sensu-plugins-slack/blob/master/bin/handler-slack.rb#L116) in the code. It suppose it would be better to check if the fields exists and log a more meaningful error message in such cases.

**Comment by mattyjones** [comment]
I am lost on this ;) I see the `unless.nil?` doing the check what else are you talking about?

**Comment by dereklwood** [comment]
I think it's actually [this line](https://github.com/sensu-plugins/sensu-plugins-slack/blob/master/bin/handler-slack.rb#L112).

If your configuration contains:
```
{
  "slack": {
    "fields": [
      "foo"
    ]
  }
}
```
where ``foo`` doesn't actually exist on the sensu client, then the ``.length`` call causes a nullpointer:
```
"output": [
    "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-0.0.4/bin/handler-slack.rb:116:in `block in payload': undefined method `length' for nil:NilClass (NoMethodError)\n",
    "\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-0.0.4/bin/handler-slack.rb:113:in `each'\n",
    "\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-0.0.4/bin/handler-slack.rb:113:in `payload'\n",
    "\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-0.0.4/bin/handler-slack.rb:94:in `post_data'\n",
    "\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-0.0.4/bin/handler-slack.rb:67:in `handle'\n",
    "\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'\n"
]
```

**Comment by dereklwood** [comment]
created PR https://github.com/sensu-plugins/sensu-plugins-slack/pull/9 for this

**Comment by mnuessler** [comment]
My initial bug report was indeed pointing to the wrong line, sorry for that mistake.

@dereklwood Thanks a lot for fixing this
