### ISSUE TITLE
Update sensu-plugin dep to 2.7 to pick up new Sensu 2 event data mapping

### ISSUE THREAD

**Issue by jspaleta** [sensu-plugins/sensu-plugins-slack#65]
sensu-plugin 2.7 has new logic to aid mutators and handlers map sensu 2 event data into sensu 1.x event data.

**Comment by majormoses** [comment]
closed via #78 and released as https://github.com/sensu-plugins/sensu-plugins-slack/blob/master/CHANGELOG.md#400---2019-04-02
